ssh_config:
  Bot_Keypad:
    HostName: 192.168.50.51
    User: ubuntu
    ProxyJump: Central
  Bot_Button:
    HostName: 192.168.50.52
    User: ubuntu
    ProxyJump: Central
  Bot_Rotary:
    HostName: 192.168.50.53
    User: ubuntu
    ProxyJump: Central
  Bot_Crater:
    HostName: 192.168.50.54
    User: ubuntu
    ProxyJump: Central
  Central:
    HostName: 10.42.0.86
    User: ubuntu
devices:
  Bot_Keypad:
    - WS_Mini_Bot
    - WS_SMACC2
  Bot_Button:
    - WS_Mini_Bot
    - WS_SMACC2
  Bot_Rotary:
    - WS_Mini_Bot
    - WS_SMACC2
  Bot_Crater:
    - WS_Mini_Bot
    - WS_SMACC2
  Central:
    - WS_Central
    - WS_Drone
    - WS_LCD
