mission:
  waypoints:
    - name: start
      coord:
        x: 0.1778
        y: 0.1778
        yaw_deg: 90.0
        frame: map

    - name: antenna_button_position
      coord:
        x: 0.1778
        y: 0.85
        yaw_deg: 90.0
        frame: map
      task:
        name: antenna_button_cali

