amcl:
  ros__parameters:
    tf_broadcast: false
    use_sim_time: false

    # Frames
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    map_topic: "/map"          # keep map subscription global, not under /bot_0 namespace

    # Laser topic (or remap via CLI)
    scan_topic: scan

    # Map topic (from nav2_map_server)
    # Usually /map by default, no need to change.

    # Particle filter params (reasonable starting point)
    min_particles: 200
    max_particles: 5000

    # Sensor model
    laser_min_range: 0.005
    laser_max_range: 1.5
    laser_max_beams: 720

    # Motion model noise (tune later)
    alpha1: 0.002
    alpha2: 0.002
    alpha3: 0.002
    alpha4: 0.002

    # How often to update
    update_min_d: 0.02
    update_min_a: 0.05
    resample_interval: 1

    # Initial pose (optional – can also be set via /initialpose)
    initial_pose_x: 0.1524
    initial_pose_y: 0.1524
    initial_pose_a: 1.5707963268
