components:
  cmd_vel_relay:
    enabled: false
    name: cmd_vel_relay
    ros__parameters:
      input_topic: "/cmd_vel"
      output_topic: "/mecanum_controller/reference"
      frame_id: "base_link"
      
  controller_manager:
    enabled: true
    params_file:
      - "ros2_controllers.yaml"

  mecanum_controller_spawner:
    enabled: true
    controller_name: mecanum_controller
    controller_manager: /bot_keypad/controller_manager

  robot_state_publisher:
    enabled: true
    parameters:
      publish_robot_description: true
      robot_description: "$(xacro mini.urdf)"

  robot_localization:
    enabled: false
    params_file: "robot_localization.yaml"

  initial_pose_publisher:
    enabled: false
    params_file: "initial_pose_publisher.yaml"

  imu_calibration:
    enabled: false
    params_file: "imu_calibration.yaml"

  wit_imu_driver:
    enabled: false
    params_file: "wit_imu_driver.yaml"

  nav2_lifecycle_manager:
    enabled: false
    params_file: "lifecycle_localization.yaml"

  nav2_map_server:
    enabled: false
    params_file: "nav2_map_server.yaml"

  nav2_stack:
    enabled: false
    params_file: "nav2_params.yaml"

  nav2_lifecycle_manager:
    enabled: false
    params_file: "lifecycle_localization.yaml"

  nav2_lifecycle_manager_navigation:
    enabled: false
    name: lifecycle_manager
    params_file: "nav2_params.yaml"

  holonomic_pi_controller:
    enabled: false
    name: holonomic_pi_controller
    params_file: "holonomic_pi_controller.yaml"

  gpio_button_event:
    enabled: false
    name: gpio_button_event
    params_file: "gpio_button_event.yaml"

  limit_switch_calibration:
    enabled: false
    package: limit_switch_calibration
    executable: calibration_node
    name: limit_switch_calibration
    params_file: "limit_switch_calibration.yaml"

  waypoint_state_machine:
    enabled: false
    package: smacc_button_nav
    executable: button_waypoint_sm
    name: waypoint_state_machine
    params_file: "waypoint_state_machine.yaml"

  pointcloud_to_laserscan:
    enabled: false
    params_file: "pointcloud_to_laserscan.yaml"
    cloud_topic: "left_depth_pcl"
    scan_topic: "left_laser_scan"

  pointcloud_filter:
    enabled: false
    params_file: "pointcloud_filter.yaml"

  uwb_triangulaion:
    enabled: false
    params_file: "uwb_config.yaml"
