# namespace: "rocker"
robot_description_file: "/ws/config/rocker.urdf"
components:
  cmd_vel_relay:
    enabled: true
    name: cmd_vel_relay
    ros__parameters:
      input_topic: "/cmd_vel"
      output_topic: "/cmd_vel_stamped"
      frame_id: "base_link"
      
  controller_manager:
    enabled: true
    params_file:
      - "/ws/config/ros2_controllers_rocker.yaml"

  mecanum_controller_spawner:
    enabled: false

  joint_state_broadcaster_spawner:
    enabled: false
    controller_name: joint_state_broadcaster
    controller_manager: /controller_manager

  rocker_bogie_controller_spawner:
    enabled: true
    controller_name: rocker_bogie_controller
    controller_manager: /controller_manager

  robot_state_publisher:
    enabled: true
    parameters:
      publish_robot_description: true
      robot_description: "$(xacro /ws/config/rocker.urdf)"

  robot_localization:
    enabled: true
    params_file: "/ws/config/robot_localization_rocker.yaml"

  initial_pose_publisher:
    enabled: true
    # x: 0.18082
    # y: 0.172
    x: 0.5
    y: 0.5
    yaw: 1.5707963268
    frame_id: map
    topic: initialpose
    delay_sec: 0.0
    tf_publish: true
    tf_parent_frame: map
    tf_child_frame: odom

  nav2_lifecycle_manager:
    enabled: false
    params_file: "/ws/config/lifecycle_localization.yaml"

  imu_calibration:
    enabled: true
    params_file: "/ws/config/imu_calibration_rocker.yaml"
