ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.5          # <- loosen for UWB (often <10 Hz)
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: bot_0/odom
    base_link_frame: bot_0/base_link
    world_frame: bot_0/odom

    initial_state: [
      0.0, 0.0, 0.0,     # start x,y near your UWB
      0.0, 0.0, 0.0,     # roll,pitch,yaw
      0.0, 0.0, 0.0,     # velocities
      0.0, 0.0, 0.0,     # angular velocities
      0.0, 0.0, 0.0      # accelerations
    ]

    # -------- IMU (yaw + yaw rate only) --------
    imu0: /bot_0/imu_data
    imu0_config: [
      false, false, false,   # x, y, z
      false, false, true,    # roll, pitch, yaw
      false, false, false,   # vx, vy, vz
      false, false, true,    # vroll, vpitch, vyaw
      false, false, false    # ax, ay, az
    ]
    imu0_queue_size: 10
    imu0_differential: false
    imu0_relative: false      # <- change to false
    imu0_remove_gravitational_acceleration: true

    # -------- UWB pose as pose0 --------
    # pose0: /bot_0/uwb_pose   # geometry_msgs/PoseWithCovarianceStamped
    # pose0_config: [
    #   true, true, false,     # x, y
    #   false, false, false,     # no orientation
    #   false, false, false,     # no linear velocities
    #   false, false, false,     # no angular velocities
    #   false, false, false      # no accelerations
    # ]
    # pose0_queue_size: 10
    # pose0_differential: false
    # pose0_relative: false
    # pose0_nodelay: false

    print_diagnostics: true
    use_control: false

    odom0: /bot_0/mecanum_controller/odometry
    odom0_config: [
      true, true, false, 
      false, false, true, 
      true, true, false, 
      false, false, true, 
      false, false, false
    ]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false