tasks:
  wait:
    type: wait
    default_duration_sec: 1.0

  imu_calibration_service:
    type: service_call
    service_name: "/trigger_imu_calibration"
    service_type: "std_srvs/srv/Empty"
    timeout_sec: 2.0

  antenna_button_cali:
    type: limit_switch_calibration
    action_name: "limit_switch_calibration"
    directions: ["left", "front"]
    pose:
      frame_id: "map"
      x: 0.1651
      y: 0.8636
      yaw_deg: 90.0
    timeout_sec: 60.0

  antenna_keypad_cali:
    type: limit_switch_calibration
    action_name: "limit_switch_calibration"
    directions: ["front", "left"]
    pose:
      frame_id: "map"
      x: 0.809625
      y: 0.1651
      yaw_deg: -90.0
    timeout_sec: 60.0

  antenna_keypad_cali_2:
    type: limit_switch_calibration
    action_name: "limit_switch_calibration"
    directions: ["front"]
    pose:
      frame_id: "map"
      x: 1.0
      y: 0.3556
      yaw_deg: -90.0
    timeout_sec: 60.0

  north_wall_cali:
    type: limit_switch_calibration
    action_name: "limit_switch_calibration"
    directions: ["right"]
    pose:
      frame_id: "map"
      x: 1.15
      y: 1.0541
      yaw_deg: -180.0
    timeout_sec: 60.0
  
  antenna_rotary_cali:
    type: limit_switch_calibration
    action_name: "limit_switch_calibration"
    directions: ["front", "right"]
    pose:
      frame_id: "map"
      x: 2.0955
      y: 1.0795
      yaw_deg: 90.0
    timeout_sec: 60.0

  south_wall_cali:
    type: limit_switch_calibration
    action_name: "limit_switch_calibration"
    directions: ["front"]
    pose:
      frame_id: "map"
      x: 0.35
      y: 0.1651
      yaw_deg: -90.0
    timeout_sec: 60.0
  
  north_wall_cali_2:
    type: limit_switch_calibration
    action_name: "limit_switch_calibration"
    directions: ["left"]
    pose:
      frame_id: "map"
      x: 1.95
      y: 1.0541
      yaw_deg: -180.0
    timeout_sec: 60.0
