<?xml version="1.0"?>
<package format="3">
  <name>uwb_i2c_reader</name>
  <version>0.1.0</version>
  <description>Reads UWB distance data from an ESP32 over I2C and publishes uwb_msgs.</description>
  <maintainer email="maintainer@example.com">Maintainer</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>i2c_manager</depend>
  <depend>uwb_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
